spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: my_jwt_secret_key
    expiration: 86400000